language: d

d:
  - dmd
  - dmd-2.071.2-b6
  - dmd-2.070.2
  - dmd-2.069.2
  - dmd-2.068.2
  - dmd-2.068.0
  - ldc
  - ldc-1.1.0-beta2
  - ldc-0.17.1

sudo: false

script:
  - dub build --build=release --config=library
  - dub test --build=unittest --config=unittest
  - dub build --build=release --config=quickstartExample
  - dub build --build=release --config=qualifiersExample
  - dub build --build=release --config=arrayCompletionExample
  - dub build --build=release --config=annotationsExample
  - dub build --build=release --config=applicationContextExample
  - dub build --build=release --config=registerOnResolveExample
  - dub build --build=release --config=constructorInjectionExample
# - dub build --build=ddox
